const boxes = [
  {
    id: 1,
    matiere: "bois",
    couleur: "chêne",
    type: "chaise",
    decoration: true,
    motif: "fleur",
    prix_final: 120,
  },
  {
    id: 2,
    matiere: "plastique",
    couleur: "blanc",
    type: "tabouret",
    decoration: false,
    motif: null,
    prix_final: 50,
  },
  {
    id: 3,
    matiere: "métal",
    couleur: "argenté",
    type: "table",
    decoration: true,
    motif: "papillon",
    prix_final: 180,
  },
  {
    id: 4,
    matiere: "bois",
    couleur: "noyer",
    type: "chaise",
    decoration: false,
    motif: null,
    prix_final: 100,
  },
  {
    id: 5,
    matiere: "plastique",
    couleur: "bleu",
    type: "tabouret",
    decoration: true,
    motif: "signe astrologique",
    prix_final: 60,
  },
  {
    id: 6,
    matiere: "métal",
    couleur: "noir",
    type: "table",
    decoration: false,
    motif: null,
    prix_final: 150,
  },
  {
    id: 7,
    matiere: "bois",
    couleur: "érable",
    type: "chaise",
    decoration: true,
    motif: "fleur",
    prix_final: 130,
  },
  {
    id: 8,
    matiere: "plastique",
    couleur: "rouge",
    type: "tabouret",
    decoration: false,
    motif: null,
    prix_final: 55,
  },
  {
    id: 9,
    matiere: "métal",
    couleur: "bronze",
    type: "table",
    decoration: true,
    motif: "papillon",
    prix_final: 200,
  },
  {
    id: 10,
    matiere: "bois",
    couleur: "merisier",
    type: "chaise",
    decoration: true,
    motif: "signe astrologique",
    prix_final: 140,
  },
];

export default boxes;
